export const formations = [
  {
    id: 1,
    title: "Favoriser le jeu libre et aménager ses espaces",
    duration: 7,
    type: "Formation Initiale",
    mode: "Présentiel",
  },
  {
    id: 2,
    title: "Construire son projet d’accueil",
    duration: 14,
    type: "Formation Initiale",
    mode: "Présentiel",
  },
  {
    id: 3,
    title: "Sensibilisation à l’environnement et activités nature",
    duration: 7,
    type: "Formation Continue",
    mode: "Distanciel",
  },
  {
    id: 4,
    title: "Accompagner le développement du langage chez l’enfant",
    duration: 14,
    type: "Formation Continue",
    mode: "Présentiel",
  },
  {
    id: 5,
    title: "Prévenir les risques domestiques à domicile",
    duration: 7,
    type: "Formation Initiale",
    mode: "Asynchrone",
  },
  {
    id: 6,
    title: "L’alimentation de l’enfant de 0 à 3 ans",
    duration: 7,
    type: "Formation Continue",
    mode: "Distanciel",
  },
  {
    id: 7,
    title: "Mieux communiquer avec les familles",
    duration: 7,
    type: "Formation Continue",
    mode: "Présentiel",
  },
  {
    id: 8,
    title: "Accompagner l’enfant dans ses découvertes sensorielles",
    duration: 7,
    type: "Formation Initiale",
    mode: "Présentiel",
  },
];
